# vim: syntax=tmux

set-option -ga update-environment ' MMUX MMUX_PANE VMUX VMUX_PANE NVIM_BUFID NVIM_SESSION_GROUP PROJECT_NAME PROJECT_REPO_ROOT GIT_REPO_PATH'
set-option -g default-terminal 'tmux-256color'
set-option -as terminal-features ",wezterm:RGB,wezterm:usstyle,tmux-256color:RGB,tmux-256color:usstyle"
set-option -g default-shell /bin/zsh

set-option -g set-titles on
set-option -g set-titles-string '#S'
set-option -g escape-time 0
set-option -g set-clipboard on
set-option -g status-interval 1
set-option -g focus-events on

set-option -gF status-style "bg=#{MACHINE_COLOR},fg=black"
set-window-option -g window-status-current-style bg=black,fg=colour15,bold
set-window-option -g window-status-style bg=colour236,fg=white

set-option -g status-left "#{E:@status-left-left}#{E:@status-left-right}"

set-option -g @status-left-left \
    ' #{?#{E:@session_icon},#{E:@session_icon} ,}'
set-option -g @status-left-right \
    '[#{E:@session_title}] '

set-option -g window-status-format \
    '#[#{E:@window-status-left-style}]#{E:@window-status-left-format}#[#{E:@window-status-right-style}]#{E:@window-status-right-format}'

set-option -gw @window-status-left-format \
    ' #{?#{E:@window_icon},#{E:@window_icon} ,}'
set-option -gw @window-status-right-format \
    '#{E:@window_title} '
set-option -gw @window-status-left-style \
    '#{window-status-style},#{?#{E:@window_icon_color},fg=#{E:@window_icon_color},}'
set-option -gw @window-status-right-style \
    '#{window-status-style},#{?#{==:#{E:@window_title_style},italic},italics,}'

set-option -g window-status-current-format \
    '#[#{E:@window-status-current-left-style}]#{E:@window-status-current-left-format}#[#{E:@window-status-current-right-style}]#{E:@window-status-current-right-format}'

set-option -gw @window-status-current-left-format \
    ' #{?#{E:@window_icon},#{E:@window_icon} ,}'
set-option -gw @window-status-current-right-format \
    '#{E:@window_title} '
set-option -gw @window-status-current-left-style \
    '#{window-status-current-style},#{?#{E:@window_icon_color},fg=#{E:@window_icon_color},}'
set-option -gw @window-status-current-right-style \
    '#{window-status-current-style},#{?#{==:#{E:@window_title_style},italic},italics,}'

set-option -g @status-empty-line-style '#{window-status-style}'

source-file "$DUMB_CLONE_HOME/mux.tmux/mux-api.tmux.conf"
