#!/bin/zsh

# Generate and replace root gitconfig
{
    printf '# %s\n' 'vim: syntax=gitconfig'
    printf '# Autogenerated by %s\n\n' "${0:a}"
    printf '%s\n' "[include]"
    for dir in "$XDG_CONFIG_HOME" "$xdg_config_dirs[@]"; do
        if [[ -d "$dir/git/gitconfig.d" ]]; then
            for file in "$dir/git/gitconfig.d"/*.gitconfig; do
                printf 'path = %s\n' "$file"
            done
        fi
    done
} > "${0:a:h}/config"
