#!/bin/zsh

if [[ ! -e "$HOME/.local/jrpc-router/local.sock" ]]; then
    mkdir -p "$HOME/.local/jrpc-router"
    chmod 0700 "$HOME/.local/jrpc-router"
    "$HOME/.local/venv/bin/python3" -m jrpc_router.jrpc_router_server \
        "$HOME/.local/jrpc-router/local.sock" \
        "$HOME/.local/jrpc-router/local-proxy.sock" \
        "$HOME/.local/jrpc-router/remote.sock" \
        "$HOME/.local/jrpc-router/remote-proxy.sock" \
        < /dev/null &> "$HOME/.local/jrpc-router/local.log" &!
    printf '%s' "$!" > "$HOME/.local/jrpc-router/local.pid"
    while [[ ! -e "$HOME/.local/jrpc-router/local.sock" ]]; do
        sleep 0.1
    done
    printf 'JRPC router running at pid %s\n' "$!"
fi

export JRPC_ROUTER_SOCKET="$HOME/.local/jrpc-router/local.sock"

if [[ -z "$SSH_CLIENT" && -z "$SSH_TTY" ]]; then
    if [[ ! -e "$HOME/.local/jrpc-router/ssh-util.sock" ]]; then
        "$HOME/.local/venv/bin/python3" -m ssh_util_service.ssh_util_server \
            "$HOME/.local/jrpc-router/ssh-util.sock" \
            "ssh-util" \
            "$HOME/.local/jrpc-router/local.sock" \
            < /dev/null &> "$HOME/.local/jrpc-router/ssh-util.log" &!
        printf '%s' "$!" > "$HOME/.local/jrpc-router/ssh-util.pid"
        printf 'SSH util running at pid %s\n' "$!"
    fi
fi
