#!/bin/zsh

# Generate and replace root gitconfig
{
    printf '# Autogenerated by %s\n\n' "${0:a}"
    printf '%s\n' '[ui]'
    printf 'ignore = %s\n' "${0:a:h}/hgignore"

    for dir in "$XDG_CONFIG_HOME" "$xdg_config_dirs[@]"; do
        if [[ -d "$dir/hg/hgrc.d" ]]; then
            for file in "$dir/hg/hgrc.d"/*.hgrc; do
                printf '%s %s\n' "%include" "$file"
            done
        fi
    done
} > "${0:a:h}/hgrc"

# Generate and replace root gitignore
{
    printf '# Autogenerated by %s\n\n' "${0:a}"
    for dir in "$XDG_CONFIG_HOME" "$xdg_config_dirs[@]"; do
        if [[ -d "$dir/hg/hgignore.d" ]]; then
            for file in "$dir/hg/hgignore.d"/*.hgignore; do
                printf 'include:%s\n' "$file"
            done
        fi
    done
} > "${0:a:h}/hgignore"
