#!/bin/zsh

function clip() {
    case "$1" in
        copy)
            jq -Rsc '{ "value": . }' | jrpc-router-autocache request ssh-util clipboard.set > /dev/null
            ;;
        paste)
            printf '%s\n' '{}' \
                | jrpc-router-autocache request ssh-util clipboard.get \
                | jq -rcj '.value'
            ;;
        *)
            printf 'Unknown clip command %s\n' "$1" >&2
            return 1
            ;;
    esac
}

clip "$@"
