#!/bin/zsh

function clip() {
    case "$1" in
        copy)
            jq -Rsc '{ "value": . }' | jrpc-autocache request "$JRPC_MESH_SOCKET" mesh \
                awe.ssh-util/SshUtilAPI.SetClipboard > /dev/null
            ;;
        paste)
            printf '%s\n' '{}' \
                | jrpc-autocache request "$JRPC_MESH_SOCKET" mesh \
                    awe.ssh-util/SshUtilAPI.GetClipboard > /dev/null \
                | jq -rcj '.value'
            ;;
        *)
            printf 'Unknown clip command %s\n' "$1" >&2
            return 1
            ;;
    esac
}

clip "$@"
