#!/bin/zsh

function ntm() {
    local session_group="$NVIM_SESSION_GROUP"
    if [[ -z "$session_group" ]]; then
        session_group="default"
    fi

    mkdir -p "$PWD/.nvim-sessions/$session_group"

    local shada_file="$PWD/.nvim-sessions/$session_group/shada"
    touch "$shada_file"

    local session_file="$PWD/.nvim-sessions/$session_group/Session.vim"
    touch "$session_file"

    USE_NTM=1 NVIM_SESSION_NAME="$session_group" nvim -i "$shada_file" -S "$session_file" "$@"
}

ntm "$@"
