#!/bin/zsh

function ntm() {
    local session_group="$NVIM_SESSION_GROUP"
    if [[ -z "$session_group" ]]; then
        session_group="default"
    fi
    local subdir="$session_group/$PWD"

    local shada_dir="$HOME/.local/state/nvim/shada/$subdir"
    local shada_file="$shada_dir/shada"
    mkdir -p "$shada_dir"
    touch "$shada_file"

    local session_dir="$HOME/.local/state/nvim/sessions/$subdir"
    local session_file="$session_dir/session.vim"
    mkdir -p "$session_dir"
    touch "$session_file"

    USE_NTM=1 NVIM_SESSION_FILE="$session_file" nvim -i "$shada_file" -S "$session_file" "$@"
}

ntm "$@"
