#!/bin/zsh

function ntm() {
    local session_group="$NVIM_SESSION_GROUP"
    if [[ -z "$session_group" ]]; then
        session_group="default"
    fi

    local shada_file="$session_group.session.vim.shada"
    touch "$shada_file"

    local session_file="$session_group.session.vim"
    touch "$session_file"

    USE_NTM=1 NVIM_SESSION_FILE="$session_file" nvim -i "$shada_file" -S "$session_file" "$@"
}

ntm "$@"
