#!/bin/zsh

function open-url() {
    setopt local_options err_return

    jq -nc --arg url "$1" '{ "url": $url }' \
        | jrpc-autocache request "$JRPC_MESH_SOCKET" mesh \
            awe.ssh-util/SshUtilAPI.OpenUrl > /dev/null
}

open-url "$@"
