#!/bin/zsh

if command -v pbpaste &> /dev/null; then
    function paste() {
        pbpaste
    }
elif command -v osc &> /dev/null; then
    function paste() {
        osc paste
    }
else
    function paste() {
        echo "No known clipboard" >&2
        return 1
    }
fi

paste "$@"
