#!/bin/zsh

if [[ "$MUX_TYPE" == nvim ]]; then
    function s() {
        if [[ "$#" -eq 0 ]]; then
            nvr -cc ":split | term"
        else
            nvr --remote -o "$@"
        fi
    }
elif [[ "$MUX_TYPE" == tmux ]]; then
    function s() {
        if [[ "$#" -eq 0 ]]; then
            tmux split-pane -b
        else
            tmux split-pane -b vim "$@"
        fi
    }
else
    function s() {
        echo "Not in a mux" >&2
        return 1
    }
fi

s "$@"
