#!/bin/zsh

if [[ -n "$USE_NTM" ]]; then
    function start_in_new_window() {
        nvr -c ":tabnew | terminal"
        nvr --remote-send "$*<enter>"
    }
elif [[ -n "$PMUX" ]]; then
    function start_in_new_window() {
        local -x TMUX="$PMUX"
        local -x TMUX_PANE="$PMUX_PANE"
        tmux new-window \;\
             send-keys -l "$1" \;\
             send-keys Enter
    }
else
    function start_in_new_window() {
        echo "Not in a mux" >&2
        return 1
    }
fi

start_in_new_window "$@"
