#!/bin/zsh

if [[ "$MUX_TYPE" == nvim ]]; then
    function t() {
        if [[ "$#" -eq 0 ]]; then
            nvr --remote-send "<m-t>"
        else
            # TODO: support localmode
            nvr --remote-tab "$@"
        fi
    }
elif [[ "$MUX_TYPE" == tmux ]]; then
    function t() {
        if [[ "$#" -eq 0 ]]; then
            tmux new-window
        else
            start_in_new_window_and_quit vim "$@"
        fi
    }
else
    function t() {
        echo "Not in a mux" >&2
        return 1
    }
fi

t "$@"
