#!/bin/zsh

function tm() {
    if [[ -z "$1" ]]; then
        echo "Session name required" >&2
        return 1
    fi

    tmux -L default has-session "-t=$1" > /dev/null 2>&1
    if [[ "$?" -eq 0 ]]; then
        tmux -L default attach-session "-t=$1"
        return 0
    fi

    tmux -L default new-session -s "$1"
}

tm "$@"
