#!/bin/zsh

if [[ -n "$NVIM" ]]; then
    function vim() {
        t "$@"
    }
elif [[ -n "$PMUX" ]]; then
    function vim() {
        local socket="$HOME/.cache/nvim/sockets/$$.pipe"
        () {
            local -x TMUX="$PMUX"
            local -x TMUX_PANE="$PMUX_PANE"
            tmux set-hook -t "$TMUX_PANE" pane-focus-in \
                "run-shell -b 'nvr --servername \"$socket\" -cc \":doautocmd User AweFocusIn\"'"
        }

        nvim --listen "$socket" "$@"

        () {
            local -x TMUX="$PMUX"
            local -x TMUX_PANE="$PMUX_PANE"
            tmux set-hook -p -t "$TMUX_PANE" -u pane-focus-in
        }
    }
else
    function vim() {
        nvim "$@"
    }
fi

vim "$@"
