#!/bin/zsh

if [[ -n "$VMUX" ]]; then
    function vm() {
        echo "Already in a vmux session" >&2
        return 1
    }
else
    function vm() {
        if [[ -z "$1" ]]; then
            echo "Session name required" >&2
            return 1
        fi

        tmux -L vmux_manager has-session "-t=$1" > /dev/null 2>&1
        if [[ "$?" -eq 0 ]]; then
            tmux -L vmux_manager attach-session "-t=$1"
            return 0
        fi

        tmux -L vmux_manager -f "$XDG_CONFIG_HOME/tmux/mmux.conf" \
            new-session -s "$1" "$XDG_CONFIG_HOME/tmux/vmux.conf.d/bin/startup"
    }
fi

vm "$@"
