#!/bin/zsh

if [[ "$MUX_TYPE" == nvim ]]; then
    function vs() {
        if [[ "$#" -eq 0 ]]; then
            nvr -cc ":vs | term"
        else
            nvr --remote -O "$@"
        fi
    }
elif [[ "$MUX_TYPE" == tmux ]]; then
    function vs() {
        if [[ "$#" -eq 0 ]]; then
            tmux split-pane -bh
        else
            tmux split-pane -bh vim "$@"
        fi
    }
else
    function vs() {
        echo "Not in a mux" >&2
        return 1
    }
fi

vs "$@"
