# Aliases
alias vim=nvim
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

export CLICOLOR=1
export LSCOLORS="GxFxCxDxBxegedabagaced"
export LS_COLORS="di=1;36;40:ln=1;35:so=1;32:pi=1;93:ex=1;31:ow=1;36"

# TODO: handle profile / PATH shell-agnostically
export PATH+=:/opt/homebrew/bin

export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
