#!/bin/zsh

if command -v pbcopy &> /dev/null; then
    function copy() {
        pbcopy
    }
elif command -v osc &> /dev/null; then
    function copy() {
        osc copy
    }
else
    function copy() {
        echo "No known clipboard" >&2
        return 1
    }
fi

copy "$@"
