#!/bin/zsh

if [[ -n "$MMUX" ]]; then
    function mmux() {
        local -x TMUX="$MMUX"
        local -x TMUX_PANE="$MMUX_PANE"
        tmux "$@"
    }
else
    function mmux() {
        tmux -L vmux_manager "$@"
    }
fi

mmux "$@"
