#!/bin/zsh

# reload a specific zsh config file
function reload() {
    local basename file_path config_dir
    basename="$1"
    file_path=""

    for config_dir in $zsh_config_path; do
        if [[ -e "$config_dir/$basename" ]]; then
            file_path="$config_dir/$basename"
            break
        fi
    done

    if [[ -z "$file_path" ]]; then
        echo "File not found in zsh_config_path" >&2
        return 1
    fi

    echo "Reloading $file_path"
    source "$file_path"
}

reload "$@"
