#!/bin/zsh

# Go to the root of the specified repo, or of the one we are in
function rr() {
    if [[ $# -gt 0 ]]; then
        local repo_root result
        for repo_root in $git_repo_path; do
            if [[ -d "$repo_root/$1" ]]; then
                result="$repo_root/$1"
                break
            fi
        done
        if [[ -n "$result" ]]; then
            cd "$result"
        else
            echo "Folder not found in search path git_repo_path" >&2
            return 1
        fi
    elif in_git_repo; then
        cd "$(git_root_dir)"
    elif [[ -n "$NVIM" ]]; then
        cd "$(nvr --remote-expr 'g:root_dir')"
    else
        echo "Not in a git repo or nvim session" >&2
        return 1
    fi
    pwd
}

rr "$@"
