#!/bin/zsh

if [[ -n "$USE_NTM" ]]; then
    function s() {
        if [[ "$#" -eq 0 ]]; then
            nvr -cc ":split | term"
        else
            nvr --remote -o "$@"
        fi
    }
elif [[ -n "$PMUX" ]]; then
    function s() {
        local -x TMUX="$PMUX"
        local -x TMUX_PANE="$PMUX_PANE"

        if [[ "$#" -eq 0 ]]; then
            tmux split-pane -b
        else
            tmux split-pane -b vim "$@"
        fi
    }
else
    function s() {
        echo "Not in a mux" >&2
        return 1
    }
fi

s "$@"
