nnoremap <SPACE> <Nop>
let mapleader=" "

for d in split($XDG_CONFIG_HOME . ':' . $XDG_CONFIG_DIRS, ':')
    for f in split(glob(d . '/vim/vimrc.d/*'), '\n')
        execute 'source' f
    endfor
endfor

if !has('nvim')
    let s:xdg_file = expand('<sfile>:p:h') . '/xdg-compliance.vim'
    execute 'source' s:xdg_file
endif
